---
title: "New Analysis"
output: html_document
date: "2026-03-07"
---
```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
library(gratia)
library(mgcv)
library(DescTools)

# Load merged data
merged_data <- read.csv("../merged_data_cleaned.csv")

#Make Weekend and Weekday Binary
merged_data <- merged_data %>%
  mutate(
    date = as.Date(hour_ts),
    hour = hour(parse_date_time(hour_ts, orders = c("ymd HMS", "ymd"))), #Note for myself! I changed this from Unix time so this needs to be ymd_hms() now instead
    day_of_week = factor(wday(date, label = TRUE), ordered = FALSE),
    is_weekend = ifelse(wday(date) %in% c(1, 7), 1,0),
    rush_hour = case_when(
      is.na(hour) ~ NA_character_, #Some data points don't have a time
      hour >= 7 & hour <= 9 ~ "Morning Rush",
      hour >= 16 & hour <= 19 ~ "Evening Rush",
      TRUE ~ "Normal Hours"
    ),
    holiday = case_when(
      date == as.Date("2018-11-26") ~ "Cyber Monday",
      date >= as.Date("2018-12-02") & date <= as.Date("2018-12-10") ~ "Hanukkah",
      TRUE ~ "None"
    ),
    cab_combo = paste(cab_type, name, sep = "-") #Combining cab_type and name
  )

lyft_data <- merged_data %>%
  filter(cab_type == "Lyft")

raw <- read.csv("../merged_data_cleaned.csv") #Shows how many data points don't have a time
sum(!grepl(":", raw$hour_ts))

class(merged_data$hour_ts)
head(merged_data$hour_ts)
```


```{r}
# check all combinations for cab_combo
unique(merged_data$cab_combo)
```


```{r}
#Compare day of week, price and cab_combo
day_of_week <- merged_data %>%
  group_by(day_of_week, cab_type, cab_combo) %>%
  summarise(
    n = n(),
    mean_price = mean(price, na.rm = TRUE),
    median_price = median(price, na.rm = TRUE)
  )
print(day_of_week, n = Inf)
```

```{r}
ggplot(merged_data, aes(x = cab_combo, y = price, fill = cab_combo)) +
  geom_boxplot(outlier.shape = NA) +
  facet_wrap(~ cab_type, scales = "free_x") +
  scale_y_continuous(limits = c(0, 60)) +
  labs(title = "Price Distribution by Cab Type",
       x = "Cab Type", y = "Price") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
```


```{r}
ggplot(data=day_of_week, mapping =aes(x=day_of_week, y=mean_price, fill=cab_combo)) +
geom_bar(
  stat = "identity",
  position = "dodge") +
geom_text(aes(label=round(mean_price, 2)), position=position_dodge(width=0.9)) +
facet_wrap(~ cab_type) +
labs(title = "Compare day of week, price and cab_combo
", x="Day of Week", y="Mean Price") +
  coord_flip() 

ggplot(data=day_of_week %>% filter(cab_type == "Lyft"), 
    mapping = aes(x=day_of_week, y=cab_combo, fill=mean_price)) +
geom_tile() +
  scale_fill_gradient(low="white", high="blue") +
geom_text(aes(label=round(mean_price, 2))) +
labs(title = "Lyft - Compare day of week, price and cab_combo
", x="Day of Week", y="Mean Price") +
theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(data=day_of_week %>% filter(cab_type == "Uber"), 
    mapping = aes(x=day_of_week, y=cab_combo, fill=mean_price)) +
geom_tile() +
  scale_fill_gradient(low="white", high="blue") +
geom_text(aes(label=round(mean_price, 2))) +
labs(title = "Uber - Compare day of week, price and cab_combo
", x="Day of Week", y="Mean Price") +
theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r}
ggplot(merged_data, aes(x = day_of_week, y = price, fill = day_of_week)) +
  geom_violin(trim = FALSE, bw = 2) +  
  geom_boxplot(width = 0.1, outlier.shape = NA) +  
  facet_wrap(~ cab_type) +
  scale_y_continuous(limits = c(0, 60)) +  
  labs(title = "Price Distribution by Day of The Week",
       x = "Day of Week", y = "Price") +
  theme_minimal() +
  theme(legend.position = "none") 
```



```{r}
#Compare weekday and weekends to price and cab_combo
weekend_summary <- merged_data %>%
  group_by(is_weekend, cab_type, cab_combo) %>%
  summarise(
    n = n(),
    mean_price = mean(price, na.rm = TRUE),
    median_price = median(price, na.rm = TRUE)
  )
print(weekend_summary)
```

```{r}
ggplot(data=weekend_summary, mapping =aes(x=factor(is_weekend, labels=c("Weekday", "Weekend")), y=mean_price, fill=cab_combo)) +
geom_bar(
  stat = "identity",
  position = "dodge") +
geom_text(aes(label=round(mean_price, 2)), position=position_dodge(width=0.9)) +
facet_wrap(~ cab_type) +
labs(title = "Compare weekday and weekends to price and cab_combo", x="Is Weekend", y="Mean Price") +
  coord_flip() 
```


```{r}
#Comparing weekend and weekday pricing to holiday pricing
holiday_summary_detailed <- merged_data %>%
  group_by(holiday, cab_type, cab_combo) %>%
  summarise(
    n = n(),
    mean_price = mean(price, na.rm = TRUE),
    median_price = median(price, na.rm = TRUE)
  )
print(holiday_summary_detailed)
```

```{r}
ggplot(data=holiday_summary_detailed, mapping =aes(x=factor(holiday, labels=c("Cyber Monday", "Hanukkah", "None")), y=mean_price, fill=cab_combo)) +
geom_bar(
  stat = "identity",
  position = "dodge") +
geom_text(aes(label=round(mean_price, 2)), position=position_dodge(width=0.9)) +
facet_wrap(~ cab_type) +
labs(title = "Comparing weekend and weekday pricing to holiday pricing", x="Holiday", y="Mean Price") +
  coord_flip() 
```
```{r}
ggplot(merged_data, aes(x = holiday, y = price, fill = holiday)) +
  geom_violin(trim = FALSE, bw = 2) +  
  geom_boxplot(width = 0.1, outlier.shape = NA) +  
  facet_wrap(~ cab_type) +
  scale_y_continuous(limits = c(0, 60)) +  
  labs(title = "Price Distribution by Holiday",
       x = "Holiday", y = "Price") +
  theme_minimal() +
  theme(legend.position = "none") 
```

```{r}
#Comparing rush hour price for weekdays to price on weekends
rush_weekdays_normal_weekends_summary <- merged_data %>%
  group_by(rush_hour, is_weekend, cab_combo, cab_type) %>%
  summarise(
    n = n(),
    mean_price = mean(price, na.rm = TRUE),
    median_price = median(price, na.rm = TRUE)
  )
print(rush_weekdays_normal_weekends_summary)
```

```{r}
ggplot(data=rush_weekdays_normal_weekends_summary, mapping =aes(x=rush_hour, y=mean_price, fill=cab_combo)) +
geom_bar(
  stat = "identity",
  position = "dodge") +
geom_text(aes(label=round(mean_price, 2)), position=position_dodge(width=0.9)) +
facet_wrap(~ is_weekend,
  labeller = labeller(is_weekend = c("0" = "Weekday", "1" = "Weekend"))) +
labs(title = "Comparing rush hour price for weekdays to price on normal weekends
", x="Rush Hour", y="Mean Price") +
  coord_flip() 

ggplot(data=rush_weekdays_normal_weekends_summary %>% filter(cab_type == "Lyft"),
    mapping = aes(x=rush_hour, y=cab_combo, fill=mean_price)) +
geom_tile() +
facet_wrap(~ is_weekend, labeller = labeller(is_weekend = c("0" = "Weekday", "1" = "Weekend"))) +
  scale_fill_gradient(low="white", high="blue") +
geom_text(aes(label=round(mean_price, 2))) +
labs(title = "Lyft - Comparing rush hour price for weekdays to price on normal weekends
", x="Rush Hour", y="Mean Price") +
theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(data=rush_weekdays_normal_weekends_summary %>% filter(cab_type == "Uber"),
    mapping = aes(x=rush_hour, y=cab_combo, fill=mean_price)) +
geom_tile() +
facet_wrap(~ is_weekend, labeller = labeller(is_weekend = c("0" = "Weekday", "1" = "Weekend"))) +
  scale_fill_gradient(low="white", high="blue") +
geom_text(aes(label=round(mean_price, 2))) +
labs(title = "Uber - Comparing rush hour price for weekdays to price on normal weekends
", x="Rush Hour", y="Mean Price") +
theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
ggplot(merged_data, aes(x = rush_hour, y = price, fill = rush_hour)) +
  geom_violin(trim = FALSE, bw = 2) +  
  geom_boxplot(width = 0.1, outlier.shape = NA) +  
  facet_wrap(~ cab_type) +
  scale_y_continuous(limits = c(0, 60)) +  
  labs(title = "Price Distribution by Rush Hour",
       x = "Rush Hour", y = "Price") +
  theme_minimal() +
  theme(legend.position = "none") 
```

```{r}
#Compare cab_combo, holiday and surge multiplier
#Show how we only have 24 slots that are on a holiday
holiday_surge_summary <- merged_data %>%
  group_by(holiday, cab_type, cab_combo) %>%
  summarise(
    n = n(),
    mean_price = mean(price, na.rm = TRUE),
    median_price = median(price, na.rm = TRUE),
    mean_surge = mean(surge_multiplier, na.rm = TRUE),
    median_surge = median(surge_multiplier, na.rm = TRUE)
  )
```

```{r}
ggplot(data=holiday_surge_summary, mapping =aes(x=cab_combo, y=mean_surge, fill=holiday)) +
geom_bar(
  stat = "identity",
  position = "dodge") +
geom_text(aes(label=round(mean_surge, 2)), position=position_dodge(width=0.9)) +
facet_wrap(~ cab_type) +
labs(title = "Compare Cab Combo, Holiday & Surge multiplier", x="Cab Type", y="Surge Pricing") +
  coord_flip() 
```

```{r}
ggplot(data=holiday_surge_summary %>% filter(cab_type == "Lyft"), 
    mapping = aes(x=holiday, y=cab_combo, fill=mean_surge)) +
geom_tile() +
  scale_fill_gradient(low="white", high="blue") +
geom_text(aes(label=round(mean_surge, 2))) +
labs(title = "Lyft - Compare Cab Combo, Holiday and Surge multiplier
", x="Holiday", y="Cab Combo") +
theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(data=holiday_surge_summary %>% filter(cab_type == "Uber"), 
    mapping = aes(x=holiday, y=cab_combo, fill=mean_surge)) +
geom_tile() +
  scale_fill_gradient(low="white", high="blue") +
geom_text(aes(label=round(mean_surge, 2))) +
labs(title = "Uber - Compare Cab Combo, Holiday and Surge multiplier
", x="Holiday", y="Cab Combo") +
theme(axis.text.x = element_text(angle = 45, hjust = 1))
```



```{r}
#Compare time of day price on normal days to time of day on holiday
normal_time_holiday_time_summary <- merged_data %>%
    filter(is_weekend==0) %>%
    group_by(hour, holiday, cab_type, cab_combo) %>%
  summarise(
    n = n(),
    mean_price = mean(price, na.rm = TRUE),
    median_price = median(price, na.rm = TRUE)
  )
```

```{r}
ggplot(data=normal_time_holiday_time_summary %>% filter(cab_type == "Lyft"), mapping =aes(x=hour, y=mean_price, color=holiday)) +
geom_line() +
facet_wrap(~ cab_combo) +
labs(title = "Compare Cost of Rides on Normal Days to Holiday", x="hour", y="mean_price") 
```


```{r}
#Compare pricing on weekday holidays to rush hour pricing
weekday_holiday_rush_summary <- merged_data %>%
    filter(is_weekend==0) %>%
    group_by(rush_hour, holiday, cab_type) %>%
  summarise(
    n = n(),
    mean_price = mean(price, na.rm = TRUE),
    median_price = median(price, na.rm = TRUE)
  )
```

```{r}
ggplot(data=weekday_holiday_rush_summary, mapping =aes(x=rush_hour, y=mean_price, fill=holiday)) +
geom_bar(
  stat = "identity",
  position = "dodge") +
facet_wrap(~ cab_type) +
geom_text(aes(label=round(mean_price, 2)), position=position_dodge(width=0.9)) +
labs(title = "Compare Pricing on Weekday Holidays to Rush Hour Pricing") +
  coord_flip()

ggplot(data=weekday_holiday_rush_summary, mapping =aes(x=rush_hour, y=holiday, fill=mean_price)) +
geom_tile() +
facet_wrap(~ cab_type) +
  scale_fill_gradient(low="white", high="red") +
geom_text(aes(label=round(mean_price, 2))) +
labs(title = "Compare pricing on weekday holidays to rush hour pricing
", x="Rush Hour", y="Holiday") +
theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
#Analyze hourly price on normal days of the week
normal_rush_dayofweek_summary <- merged_data %>%
    filter(holiday=="None") %>%
    group_by(hour, day_of_week, cab_type, cab_combo) %>%
  summarise(
    n = n(),
    mean_price = mean(price, na.rm = TRUE),
    median_price = median(price, na.rm = TRUE)
  )
```
```{r}
ggplot(data=normal_rush_dayofweek_summary %>% filter(cab_type == "Lyft"), mapping =aes(x=hour, y=mean_price, color=day_of_week)) +
geom_line() +
facet_wrap(~ cab_combo) +
labs(title = "Analyze hourly price on normal days of the week
", x="hour", y="mean_price") 

ggplot(data=normal_rush_dayofweek_summary %>% filter(cab_type == "Uber"), mapping =aes(x=hour, y=mean_price, color=day_of_week)) +
geom_line() +
facet_wrap(~ cab_combo) +
labs(title = "Analyze Hourly Price on Normal Days of the Week
", x="Hour", y="Mean Price") 
```

```{r}
#Looking at the plots above time has little to no impact on the prices. The cab type is what has the most influence on the price of Uber and Lyft rides.
```



```{r}
#How big a difference is there in the days over the full time period
merged_data %>%
    group_by(date) %>%
  summarise(
    n = n(),
  )
```



```{r}
#How many people use Uber vs. Lyft
merged_data %>%
    group_by(cab_type) %>%
  summarise(
    n = n(),
  )
```

```{r}
#How many people use each cab_type
merged_data %>%
    group_by(cab_combo) %>%
  summarise(
    n = n(),
  )
#The numbers are all very similar. Did the creator of the dataset do this on purpose or is this the true distribution of rides chosen.
```



```{r}
#Modelling GLM
glm_model_price <- glm(price ~ holiday + day_of_week + hour + cab_combo + surge_multiplier,
                      data = merged_data,
                      family = Gamma(link = "log"))
summary(glm_model_price)
appraise(glm_model_price)
PseudoR2(glm_model_price, which = NULL)
```

```{r}
#Modelling GAM
gam_model_price <- gam(price ~ holiday + day_of_week + s(hour) + cab_combo + surge_multiplier,
                      data = merged_data,
                      family = Gamma(link = "log"))
summary(gam_model_price)
appraise(gam_model_price)
draw(gam_model_price)
#the plot is non-linear however since hour is the only smoothable variable and the rest are categorical GLM may be best overall.

```


```{r}
AIC(gam_model_price, glm_model_price)
#the GLM fits better and since most of the variables in this question are categorical then we will continue with the GLM.
```



```{r}
#References
# https://www.neonscience.org/resources/learning-hub/tutorials/dc-convert-date-time-posix-r#:~:text=POSIXct-,The%20as.,often%20your%20local%20time%20zone.
#https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/grep
#https://r-graph-gallery.com/218-basic-barplots-with-ggplot2.html
#https://www.r-bloggers.com/2021/09/adding-text-labels-to-ggplot2-bar-chart-2/
#https://r-graph-gallery.com/79-levelplot-with-ggplot2.html
#https://www.codecademy.com/resources/docs/general/file-paths
#https://cran.r-project.org/web/packages/gratia/vignettes/gratia.html
#https://stats.stackexchange.com/questions/664508/model-diagnostics-for-gam-generalised-additive-model
#https://gavinsimpson.github.io/gratia/
#https://www.atlassian.com/data/charts/violin-plot-complete-guide
#https://ggplot2.tidyverse.org/reference/geom_violin.html#:~:text=Source:%20R/geom%2Dviolin,same%20way%20as%20a%20boxplot.
#https://search.r-project.org/CRAN/refmans/DescTools/html/PseudoR2.html
#https://www.rdocumentation.org/packages/DescTools/versions/0.99.60
#https://stats.stackexchange.com/questions/82105/mcfaddens-pseudo-r2-interpretation
#https://psychology.town/statistics/dispersion-concept-data-analysis/
```

